name: "Duplicate Guard"
description: "Blocks pull requests with unintentionally duplicated files"
author: "Chris Rutkowski"
inputs:
  ignore_file:
    description: "Path to the ignore file"
    required: true
    default: "./duplicate_guard.ignore"

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Get changed files
      if: ${{ github.event_name == 'pull_request' }}
      id: changed-files
      uses: tj-actions/changed-files@v45
      with:
        json: true
        write_output_files: true
        safe_output: false

    - name: Get all files
      if: ${{ github.event_name != 'pull_request' }}
      run: |
        mkdir -p .github/outputs/
        find . -type f | sed 's|^\./||' | jq -R . | jq -s . > .github/outputs/all_repo_files.json
      shell: bash

    - name: Run Duplicate Guard
      run: |
        python3 ${GITHUB_ACTION_PATH}/duplicate_guard.py ${{ inputs.ignore_file }} .github/outputs/modified_files.json .github/outputs/added_files.json .github/outputs/all_repo_files.json
      shell: bash
